# 关闭模板引擎缓存
spring:
  thymeleaf:
    cache: false
  #国际化配置文件位置
  messages:
    basename: i18n.login

  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
